disabled_rules:
  - trailing_whitespace
  - force_unwrapping
  - implicitly_unwrapped_optional
  - todo
  - opening_brace

opt_in_rules:
  - empty_count
  - explicit_init
  - multiline_parameters
  - overridden_super_call
  - redundant_nil_coalescing
  - sorted_imports
  - unneeded_parentheses_in_closure_argument

excluded:
  - .build
  - .swiftpm
  - LoRaCueManager.xcodeproj
  - LoRaCueManager.xcworkspace
  - LoRaCueManagerPackage

line_length:
  warning: 120
  error: 150

file_length:
  warning: 500
  error: 1000

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 50
  error: 100

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y

custom_rules:
  no_print:
    name: "No Print Statements"
    regex: '\bprint\('
    message: "Use Logger instead of print()"
    severity: warning
